model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss # name of the logged metric which determines when model is improving
  mode: min # can be "max" or "min"
  save_top_k: 3 # save k best models (determined by above metric) | if -1, all models are saved.
  save_last: True # additionally, always save model from last epoch
  verbose: False
  dirpath: checkpoints/
  filename: epoch_{epoch:03d}
  auto_insert_metric_name: False